# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWSOps'
    regionName: 'us-east-1'
    stackName: 'vpc-eks'
    templateSource: 'file'
    templateFile: 'amazon-eks-vpc-private-subnets.yaml'
    capabilityAutoExpand: true
